### ISSUE TITLE
Error undefined property missing ':'

### ISSUE THREAD

**Issue by aboutqx** [youzan/sprite-loader#1]
node6.9.5 error generate css.Seems an error with dependency 'css' parser.
That happens when using sass-loader in the chain.

**Comment by yurii-sorokin** [comment]
+1

**Comment by vinnyguitar** [comment]
@aboutqx The css lib may not support some css rule.I will use post-css to rewrite.

**Comment by aboutqx** [comment]
That will be fine.

**Comment by Eireen** [comment]
I had the same problem. The following configuration works for me (Node v7.10.0, webpack 2.6.1) - note the [importLoaders](https://webpack.js.org/loaders/css-loader/#importloaders) option:

```js
{
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
        use: [
            {
                loader: 'css-loader',
                options: { importLoaders: 1 }
            },
            {
                loader: 'sprite-loader',
                options: { name: "sprite.[hash].png" }
            }
        ]
    })
}
```

**Comment by hxfdarling** [comment]
+1

**Comment by bbb324** [comment]
+1

**Comment by chenhm123** [comment]
+1

**Comment by karataev** [comment]
The same error happens with css-loader in the chain.

**Comment by vinnyguitar** [comment]
It gives an error config example in old readme. Make sure sprite-loader is in the front of css-loader like follow.
![image](https://user-images.githubusercontent.com/3080098/29132508-065eb2ce-7d63-11e7-8d3d-7129a35ceba8.png)
